### ISSUE TITLE
Stack generation have breaking changes from 2021-09-18 to latest

### ISSUE THREAD

**Issue by Ousret** [tiangolo/docker-with-compose#33]
The latest push did break some of our deployments.

Initially posted in https://github.com/tiangolo/docker-with-compose/issues/32 but does not per se have the same issue.

**Before:**

```Dockerfile
FROM tiangolo/docker-with-compose:2021-09-18
WORKDIR /tmp
COPY docker-compose.yml ./
CMD ['docker-compose', '-f', 'docker-compose.yml', 'config']
```

**After:**

```Dockerfile
FROM tiangolo/docker-with-compose:latest
WORKDIR /tmp
COPY docker-compose.yml ./
CMD ['docker-compose', '-f', 'docker-compose.yml', 'config']
```

Basic file input `docker-compose.yml`

```yaml
version: '3.8'
 
services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: azerty
      POSTGRES_DB: api
    volumes:
      - app-db:/var/lib/postgresql/data
 
volumes:
  app-db:
```

**Output before:**
```yaml
services:
  db:
    environment:
      POSTGRES_DB: api
      POSTGRES_PASSWORD: azerty
      POSTGRES_USER: api
    image: postgres:14-alpine
    volumes:
    - app-db:/var/lib/postgresql/data:rw
version: '3.8'
volumes:
  app-db: {}
```

**Output now:**
```yaml
name: tmp
services:
  db:
    environment:
      POSTGRES_DB: api
      POSTGRES_PASSWORD: azerty
      POSTGRES_USER: api
    image: postgres:14-alpine
    networks:
      default: null
    volumes:
    - type: volume
      source: app-db
      target: /var/lib/postgresql/data
      volume: {}
networks:
  default:
    name: tmp_default
volumes:
  app-db:
    name: tmp_app-db
```

- `version: '3.8'` is not present on the generated stack.yml (the target host fallback to `version: 1` which is problematic. even though it is on our (input) files.
- volumes descriptions have changed unexpectedly so there are re-created (not found)
- it seems that this image generates a compose-compliant (v2) schema file while the command docker stack is not ready.

**from remote, not actually the docker-with-compose image**
```shell
docker stack deploy -c docker-stack.yml --with-registry-auth "xxxx"
unsupported Compose file version: 1.0
```

hint: the `docker-stack.yml` seems to be generated using compose v2 instead of docker-compose legacy version.

**Comment by do-web** [comment]
I have the problem, i am getting now "unsupported Compose file version: 1.0"

With my docker compose file, before the update all works fine.

```
version: "3.7"

services:
  km:
    image: ${IMAGE}
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/public
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        caddy: ${CADDY_DOMAIN}
        caddy.reverse_proxy: "{{upstreams 80}}"

networks:
  default:
    external:
      name: caddy_caddy
```
