### ISSUE TITLE
add make

### ISSUE THREAD

**Issue by kvnwolf** [tiangolo/docker-with-compose#6]
Currently, I have to install make everytime I want to run `make` commands. IMO, a good amount of people may be using `make` to run `docker-compose` commands.

Is it out of the scope to add the `make` installation to this package?

This is my current `.gitlab-ci.yml` file
```yml
image: tiangolo/docker-with-compose

services:
  - docker:dind

before_script:
  - apk add --update make

stages:
  - lint
  - test

lint:
  stage: lint
  script:
    - make ci-lint

test:
  stage: test
  script:
    - make ci-test
```
