### ISSUE TITLE
docker-compose up -d fails

### ISSUE THREAD

**Issue by roychowdhuryrohit-dev** [tiangolo/docker-with-compose#9]
Error - 

Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

**Comment by IzioDev** [comment]
I have the same issue here using the gitlab-ci, here's my file:

```yml
test_autoresponder:
  stage: test
  only:
    refs:
      - merge_requests
    changes:
      - stacks/autoresponder/**/*
  image:
    name: tiangolo/docker-with-compose:latest
  services:
    - docker:dind
  script:
    - docker-compose -p test -f docker-compose.test.yml up -d
```

I even tried with sudo before the `docker-compose` command, but it didn't help.
